# Generated by Django 5.1.4 on 2024-12-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_task_descr'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('uncomplete', 'Не выполена'), ('complete', 'Выполнена')], default='uncomplete', max_length=100),
        ),
    ]
