# Generated by Django 5.1.4 on 2024-12-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('uncomplete', 'Не выполена'), ('complete', 'Выполнена'), ('in_progress', 'В процессе')], default='uncomplete', max_length=100),
        ),
    ]
